// RUN: mlir-translate --import-dxsa-bin %S/inputs/bad_ftoi.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed|skipOptimization>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 64 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand.imm {imm = dense<2139095039> : vector<1xi32>}
// CHECK:         dxsa.instruction "ftou" %[[OPERAND_0]], %[[OPERAND_1]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_1]] {mask = 128 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand.imm {imm = dense<-8388609> : vector<1xi32>}
// CHECK:         dxsa.instruction "ftou" %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_2]] {mask = 48 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand.imm {imm = dense<[2139095039, -8388609, 0, 0]> : vector<4xi32>}
// CHECK:         dxsa.instruction "ftoi" %[[OPERAND_4]], %[[OPERAND_5]]
// CHECK:         dxsa.instruction "ret"

