// RUN: mlir-translate --import-dxsa-bin %S/inputs/bool1.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "firstbit_hi" %[[OPERAND_1]], %[[OPERAND_2]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]] {modifier = 1 : i32, num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand.imm {imm = dense<31> : vector<1xi32>}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_3]], %[[OPERAND_4]], %[[OPERAND_5]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_5]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_6]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand.imm {imm = dense<-1> : vector<1xi32>}
// CHECK:         dxsa.instruction "movc" %[[OPERAND_6]], %[[OPERAND_7]], %[[OPERAND_8]], %[[OPERAND_9]]
// CHECK:         dxsa.instruction "ret"

