// RUN: mlir-translate --import-dxsa-bin %S/inputs/call1.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "switch" %[[OPERAND_2]]
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand.imm {imm = dense<1> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_3]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "call" %[[OPERAND_4]]
// CHECK:         dxsa.instruction "break"
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand.imm {imm = dense<2> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_5]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_4]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "call" %[[OPERAND_6]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "default"
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_5]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "call" %[[OPERAND_7]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "endswitch"
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_6]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_8]], %[[OPERAND_9]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_8]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "label" %[[OPERAND_10]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_9]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand.imm {imm = dense<1084227584> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_10]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "label" %[[OPERAND_13]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_11]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_14]], %[[OPERAND_15]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_13]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "label" %[[OPERAND_16]]
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_14]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand.imm {imm = dense<1077936128> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_17]], %[[OPERAND_18]]
// CHECK:         dxsa.instruction "ret"

