// RUN: mlir-translate --import-dxsa-bin %S/inputs/cbuffer3.51.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 16, lbound = 17, ubound = 80, space = 0>, <dynamicIndexed>
// CHECK:         dxsa.dcl_constant_buffer <id = 1, size = 16, lbound = 77, ubound = 108, space = 3>, <dynamicIndexed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 112 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand.imm {imm = dense<12> : vector<1xi32>}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_1]], %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_3]] {mask = 96 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_4]] {num_components = 4 : i32, swizzle = dense<[1, 1, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_4]], %[[OPERAND_5]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_5]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, one = 2 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.rel.imm %[[OPERAND_7]] {imm = 17 : i32, op = "add"}
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_9]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.rel %[[OPERAND_8]]
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_6]], %[[INDEX_8]], %[[INDEX_10]] {num_components = 4 : i32, one = 2 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_6]], %[[OPERAND_9]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_11]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_13]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.rel.imm %[[OPERAND_11]] {imm = 77 : i32, op = "add"}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.rel %[[OPERAND_12]]
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_12]], %[[INDEX_14]], %[[INDEX_16]] {num_components = 4 : i32, swizzle = dense<[3, 1, 1, 1]> : vector<4xi32>, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_10]], %[[OPERAND_13]]
// CHECK:         dxsa.instruction "ret"

