// RUN: mlir-translate --import-dxsa-bin %S/inputs/double3.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed|enableDoublePrecisionFloatOps>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 192 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_2]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 2
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_3]], %[[OPERAND_4]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_5]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "deq" %[[OPERAND_5]], %[[OPERAND_6]], %[[OPERAND_7]]
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_8]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {num_components = 4 : i32, swizzle = dense<[0, 0, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_8]], %[[OPERAND_9]]
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_10]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_11]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dne" %[[OPERAND_10]], %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_13]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_14]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "and" %[[OPERAND_13]], %[[OPERAND_14]], %[[OPERAND_15]]
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_16]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_17]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_18]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dlt" %[[OPERAND_16]], %[[OPERAND_17]], %[[OPERAND_18]]
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_19]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_20]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_21]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dmul" %[[OPERAND_19]], %[[OPERAND_20]], %[[OPERAND_21]]
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_22]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_23]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_24]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_22]], %[[OPERAND_23]], %[[OPERAND_24]]
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_25]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand %[[INDEX_26]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_27]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dlt" %[[OPERAND_25]], %[[OPERAND_26]], %[[OPERAND_27]]
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_28]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_29]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_30]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "and" %[[OPERAND_28]], %[[OPERAND_29]], %[[OPERAND_30]]
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_31]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_32]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand %[[INDEX_33]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "and" %[[OPERAND_31]], %[[OPERAND_32]], %[[OPERAND_33]]
// CHECK:         dxsa.instruction "ret"

