// RUN: mlir-translate --import-dxsa-bin %S/inputs/double6.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed|enableDoublePrecisionFloatOps>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 5>, <dynamicIndexed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_2]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 2
// CHECK:         dxsa.dcl_indexable_temp x0[6], 4
// CHECK:         dxsa.dcl_indexable_temp x1[4], 4
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]], %[[INDEX_4]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand.imm {imm = dense<[1075838976, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_3]], %[[OPERAND_4]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_5]], %[[INDEX_6]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand.imm {imm = dense<[1072693248, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_5]], %[[OPERAND_6]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]], %[[INDEX_8]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand.imm {imm = dense<[1073741824, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_7]], %[[OPERAND_8]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]], %[[INDEX_10]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand.imm {imm = dense<[4611686019501947617, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_9]], %[[OPERAND_10]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_11]], %[[INDEX_12]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand.imm {imm = dense<[1075576832, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_13]], %[[INDEX_14]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand.imm {imm = dense<[1077968896, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_15]], %[[INDEX_16]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand.imm {imm = dense<[1072693248, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_15]], %[[OPERAND_16]]
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_17]], %[[INDEX_18]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand.imm {imm = dense<[1073741824, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_17]], %[[OPERAND_18]]
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_19]], %[[INDEX_20]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand.imm {imm = dense<[4611686019501947617, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_19]], %[[OPERAND_20]]
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_21]], %[[INDEX_22]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand.imm {imm = dense<[1075576832, 0]> : vector<2xi64>}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_21]], %[[OPERAND_22]]
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_23]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_24]], %[[INDEX_25]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 0]> : vector<4xi32>, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_23]], %[[OPERAND_24]]
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_26]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand %[[INDEX_28]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.rel %[[OPERAND_26]]
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_27]], %[[INDEX_29]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 3 : i32}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_25]], %[[OPERAND_27]]
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_30]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_31]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_33]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.rel.imm %[[OPERAND_30]] {imm = 1 : i32, op = "add"}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_32]], %[[INDEX_34]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 8 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_28]], %[[OPERAND_29]], %[[OPERAND_31]]
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_35]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand %[[INDEX_37]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_38:.*]] = dxsa.index.rel %[[OPERAND_33]]
// CHECK:         %[[OPERAND_34:.*]] = dxsa.operand %[[INDEX_36]], %[[INDEX_38]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 3 : i32}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_32]], %[[OPERAND_34]]
// CHECK:         %[[INDEX_39:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_35:.*]] = dxsa.operand %[[INDEX_39]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_40:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_36:.*]] = dxsa.operand %[[INDEX_40]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_41:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_37:.*]] = dxsa.operand %[[INDEX_41]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_35]], %[[OPERAND_36]], %[[OPERAND_37]]
// CHECK:         %[[INDEX_42:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_38:.*]] = dxsa.operand %[[INDEX_42]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_43:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_39:.*]] = dxsa.operand %[[INDEX_43]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 0]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_38]], %[[OPERAND_39]]
// CHECK:         %[[INDEX_44:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_40:.*]] = dxsa.operand %[[INDEX_44]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_45:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_41:.*]] = dxsa.operand %[[INDEX_45]] {num_components = 4 : i32, swizzle = dense<[0, 0, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_40]], %[[OPERAND_41]]
// CHECK:         %[[INDEX_46:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_42:.*]] = dxsa.operand %[[INDEX_46]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_47:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_43:.*]] = dxsa.operand %[[INDEX_47]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_48:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_44:.*]] = dxsa.operand %[[INDEX_48]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_42]], %[[OPERAND_43]], %[[OPERAND_44]]
// CHECK:         %[[INDEX_49:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_45:.*]] = dxsa.operand %[[INDEX_49]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_50:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_46:.*]] = dxsa.operand %[[INDEX_50]] {num_components = 4 : i32, swizzle = dense<[0, 0, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_45]], %[[OPERAND_46]]
// CHECK:         %[[INDEX_51:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_47:.*]] = dxsa.operand %[[INDEX_51]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_52:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_48:.*]] = dxsa.operand %[[INDEX_52]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_53:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_49:.*]] = dxsa.operand %[[INDEX_53]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_47]], %[[OPERAND_48]], %[[OPERAND_49]]
// CHECK:         %[[INDEX_54:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_50:.*]] = dxsa.operand %[[INDEX_54]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_55:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_51:.*]] = dxsa.operand %[[INDEX_55]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_56:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_52:.*]] = dxsa.operand %[[INDEX_56]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_50]], %[[OPERAND_51]], %[[OPERAND_52]]
// CHECK:         %[[INDEX_57:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_58:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_53:.*]] = dxsa.operand %[[INDEX_58]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_59:.*]] = dxsa.index.rel %[[OPERAND_53]]
// CHECK:         %[[OPERAND_54:.*]] = dxsa.operand %[[INDEX_57]], %[[INDEX_59]] {mask = 48 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_60:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_55:.*]] = dxsa.operand %[[INDEX_60]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_54]], %[[OPERAND_55]]
// CHECK:         %[[INDEX_61:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_56:.*]] = dxsa.operand %[[INDEX_61]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_62:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[INDEX_63:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_57:.*]] = dxsa.operand %[[INDEX_63]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_64:.*]] = dxsa.index.rel %[[OPERAND_57]]
// CHECK:         %[[OPERAND_58:.*]] = dxsa.operand %[[INDEX_62]], %[[INDEX_64]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 3 : i32}
// CHECK:         dxsa.instruction "dmov" %[[OPERAND_56]], %[[OPERAND_58]]
// CHECK:         %[[INDEX_65:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_59:.*]] = dxsa.operand %[[INDEX_65]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_66:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_60:.*]] = dxsa.operand %[[INDEX_66]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_67:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_61:.*]] = dxsa.operand %[[INDEX_67]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_59]], %[[OPERAND_60]], %[[OPERAND_61]]
// CHECK:         %[[INDEX_68:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_62:.*]] = dxsa.operand %[[INDEX_68]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_69:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_63:.*]] = dxsa.operand %[[INDEX_69]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_62]], %[[OPERAND_63]]
// CHECK:         dxsa.instruction "ret"

