// RUN: mlir-translate --import-dxsa-bin %S/inputs/double5.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed|enableDoublePrecisionFloatOps|enableDoubleExtensions>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_2]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 2
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 0]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_3]], %[[OPERAND_4]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_5]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dtof" %[[OPERAND_5]], %[[OPERAND_6]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_8]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "ftod" %[[OPERAND_7]], %[[OPERAND_8]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_10]] {num_components = 4 : i32, swizzle = dense<[0, 0, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_9]], %[[OPERAND_10]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_11]] {mask = 64 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dtoi" %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_13]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_14]] {num_components = 4 : i32, one = 2 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "itod" %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_15]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_16]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_17]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_15]], %[[OPERAND_16]], %[[OPERAND_17]]
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_18]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_19]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_20]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_18]], %[[OPERAND_19]], %[[OPERAND_20]]
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_21]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_22]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_23]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_21]], %[[OPERAND_22]], %[[OPERAND_23]]
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_24]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_25]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand %[[INDEX_26]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_24]], %[[OPERAND_25]], %[[OPERAND_26]]
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_27]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_28]] {num_components = 4 : i32, swizzle = dense<[0, 0, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_27]], %[[OPERAND_28]]
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_29]] {mask = 64 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_30]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dtou" %[[OPERAND_29]], %[[OPERAND_30]]
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_31]] {mask = 192 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_32]] {num_components = 4 : i32, one = 2 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "utod" %[[OPERAND_31]], %[[OPERAND_32]]
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand %[[INDEX_33]] {mask = 48 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_34:.*]] = dxsa.operand %[[INDEX_34]] {num_components = 4 : i32, swizzle = dense<[2, 3, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_35:.*]] = dxsa.operand %[[INDEX_35]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "dadd" %[[OPERAND_33]], %[[OPERAND_34]], %[[OPERAND_35]]
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_36:.*]] = dxsa.operand %[[INDEX_36]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_37:.*]] = dxsa.operand %[[INDEX_37]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_36]], %[[OPERAND_37]]
// CHECK:         dxsa.instruction "ret"

