// RUN: mlir-translate --import-dxsa-bin %S/inputs/eval.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 112 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_2]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_3]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_4]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_5]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_5]]
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 6 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_6]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 7 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_7]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 3
// CHECK:         dxsa.dcl_index_range <type = input, components = 4, mask = <x, y, z, w>, index = [2]>, 6
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_8]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_10]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "eval_sample_index" %[[OPERAND_8]], %[[OPERAND_9]], %[[OPERAND_10]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_11]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand.imm {imm = dense<3> : vector<1xi32>}
// CHECK:         dxsa.instruction "eval_sample_index" %[[OPERAND_11]], %[[OPERAND_12]], %[[OPERAND_13]]
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_13]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_14]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_14]], %[[OPERAND_15]], %[[OPERAND_16]]
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_16]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_17]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "eval_centroid" %[[OPERAND_17]], %[[OPERAND_18]]
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_18]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_19]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_20]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_19]], %[[OPERAND_20]], %[[OPERAND_21]]
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_21]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_22]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand.imm {imm = dense<[-2, 5, 0, 0]> : vector<4xi32>}
// CHECK:         dxsa.instruction "eval_snapped" %[[OPERAND_22]], %[[OPERAND_23]], %[[OPERAND_24]]
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_23]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand %[[INDEX_24]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_25]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_25]], %[[OPERAND_26]], %[[OPERAND_27]]
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_26]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_27]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_28]], %[[OPERAND_29]]
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_28]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_29]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.rel.imm %[[OPERAND_31]] {imm = 2 : i32, op = "add"}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_30]] {num_components = 4 : i32, swizzle = dense<[2, 2, 0, 1]> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand %[[INDEX_31]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "eval_sample_index" %[[OPERAND_30]], %[[OPERAND_32]], %[[OPERAND_33]]
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_34:.*]] = dxsa.operand %[[INDEX_32]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_35:.*]] = dxsa.operand %[[INDEX_33]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_36:.*]] = dxsa.operand %[[INDEX_34]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_34]], %[[OPERAND_35]], %[[OPERAND_36]]
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_37:.*]] = dxsa.operand %[[INDEX_35]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_38:.*]] = dxsa.operand %[[INDEX_36]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_37]], %[[OPERAND_38]]
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_39:.*]] = dxsa.operand %[[INDEX_37]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_38:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_40:.*]] = dxsa.operand %[[INDEX_38]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_39:.*]] = dxsa.index.rel.imm %[[OPERAND_40]] {imm = 2 : i32, op = "add"}
// CHECK:         %[[OPERAND_41:.*]] = dxsa.operand %[[INDEX_39]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "eval_centroid" %[[OPERAND_39]], %[[OPERAND_41]]
// CHECK:         %[[INDEX_40:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_42:.*]] = dxsa.operand %[[INDEX_40]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_41:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_43:.*]] = dxsa.operand %[[INDEX_41]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_42:.*]] = dxsa.index.rel.imm %[[OPERAND_43]] {imm = 2 : i32, op = "add"}
// CHECK:         %[[OPERAND_44:.*]] = dxsa.operand %[[INDEX_42]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[OPERAND_45:.*]] = dxsa.operand.imm {imm = dense<[-2, 5, 0, 0]> : vector<4xi32>}
// CHECK:         dxsa.instruction "eval_snapped" %[[OPERAND_42]], %[[OPERAND_44]], %[[OPERAND_45]]
// CHECK:         %[[INDEX_43:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_46:.*]] = dxsa.operand %[[INDEX_43]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_44:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_47:.*]] = dxsa.operand %[[INDEX_44]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_45:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_48:.*]] = dxsa.operand %[[INDEX_45]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_46]], %[[OPERAND_47]], %[[OPERAND_48]]
// CHECK:         %[[INDEX_46:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_49:.*]] = dxsa.operand %[[INDEX_46]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_47:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_50:.*]] = dxsa.operand %[[INDEX_47]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_48:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_51:.*]] = dxsa.operand %[[INDEX_48]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_49]], %[[OPERAND_50]], %[[OPERAND_51]]
// CHECK:         dxsa.instruction "ret"

