// RUN: mlir-translate --import-dxsa-bin %S/inputs/gs2.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 1>, <immediateIndexed>
// CHECK:         dxsa.dcl_input <type = input, components = 4, mask = <x, y, z, w>, index = [1, 0]>
// CHECK:         dxsa.dcl_temps 2
// CHECK:         dxsa.dcl_input_primitive  point
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "dcl_stream" %[[OPERAND_0]]
// CHECK:         dxsa.dcl_output_topology  pointlist
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x, y, z, w>, index = [0]>, <position>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y>, index = [1]>
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "dcl_stream" %[[OPERAND_1]]
// CHECK:         dxsa.dcl_output_topology  pointlist
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z>, index = [0]>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [1]>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [2]>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [3]>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z>, index = [4]>
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "dcl_stream" %[[OPERAND_2]]
// CHECK:         dxsa.dcl_output_topology  pointlist
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x, y, z, w>, index = [0]>, <position>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y>, index = [1]>
// CHECK:         dxsa.dcl_max_output_vertex_count 12
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 112 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]], %[[INDEX_5]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 0]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "ftou" %[[OPERAND_3]], %[[OPERAND_4]]
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_6]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand.imm {imm = dense<1110441984> : vector<4xi32>}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]], %[[INDEX_8]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mul" %[[OPERAND_5]], %[[OPERAND_6]], %[[OPERAND_7]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_9]], %[[INDEX_10]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "if" %[[OPERAND_8]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_11]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_12]], %[[INDEX_13]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_9]], %[[OPERAND_10]]
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_14]] {mask = 48 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_15]], %[[INDEX_16]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 0]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_17]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "emit_stream" %[[OPERAND_13]]
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_18]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "cut_stream" %[[OPERAND_14]]
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_19]] {mask = 128 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_20]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_15]], %[[OPERAND_16]]
// CHECK:         dxsa.instruction "else"
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_21]] {mask = 128 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_22]], %[[INDEX_23]] {num_components = 4 : i32, one = 3 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "ftou" %[[OPERAND_17]], %[[OPERAND_18]]
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_24]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_25]] {num_components = 4 : i32, one = 3 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_19]], %[[OPERAND_20]]
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_26]] {mask = 96 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_27]] {num_components = 4 : i32, swizzle = dense<[1, 1, 2, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_21]], %[[OPERAND_22]]
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_28]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_23]], %[[OPERAND_24]]
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_29]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_25]], %[[OPERAND_26]]
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_30]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_31]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_27]], %[[OPERAND_28]]
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_32]] {mask = 112 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_33]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 0]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_29]], %[[OPERAND_30]]
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_34]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "emit_stream" %[[OPERAND_31]]
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_35]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "cut_stream" %[[OPERAND_32]]
// CHECK:         dxsa.instruction "endif"
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand %[[INDEX_36]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_34:.*]] = dxsa.operand %[[INDEX_37]] {num_components = 4 : i32, one = 3 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_33]], %[[OPERAND_34]]
// CHECK:         %[[INDEX_38:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_35:.*]] = dxsa.operand %[[INDEX_38]] {mask = 96 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_39:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_36:.*]] = dxsa.operand %[[INDEX_39]] {num_components = 4 : i32, swizzle = dense<[1, 1, 2, 1]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_35]], %[[OPERAND_36]]
// CHECK:         %[[INDEX_40:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_37:.*]] = dxsa.operand %[[INDEX_40]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_38:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_37]], %[[OPERAND_38]]
// CHECK:         %[[INDEX_41:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_39:.*]] = dxsa.operand %[[INDEX_41]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_40:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_39]], %[[OPERAND_40]]
// CHECK:         %[[INDEX_42:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_41:.*]] = dxsa.operand %[[INDEX_42]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_43:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_42:.*]] = dxsa.operand %[[INDEX_43]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_41]], %[[OPERAND_42]]
// CHECK:         %[[INDEX_44:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_43:.*]] = dxsa.operand %[[INDEX_44]] {mask = 112 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_45:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_44:.*]] = dxsa.operand %[[INDEX_45]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 0]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_43]], %[[OPERAND_44]]
// CHECK:         %[[INDEX_46:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_45:.*]] = dxsa.operand %[[INDEX_46]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "emit_stream" %[[OPERAND_45]]
// CHECK:         %[[INDEX_47:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_46:.*]] = dxsa.operand %[[INDEX_47]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "cut_stream" %[[OPERAND_46]]
// CHECK:         %[[INDEX_48:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_47:.*]] = dxsa.operand %[[INDEX_48]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_49:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_50:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_48:.*]] = dxsa.operand %[[INDEX_49]], %[[INDEX_50]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_47]], %[[OPERAND_48]]
// CHECK:         %[[INDEX_51:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_49:.*]] = dxsa.operand %[[INDEX_51]] {mask = 48 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_52:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_53:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_50:.*]] = dxsa.operand %[[INDEX_52]], %[[INDEX_53]] {num_components = 4 : i32, swizzle = dense<[0, 1, 0, 0]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_49]], %[[OPERAND_50]]
// CHECK:         %[[INDEX_54:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_51:.*]] = dxsa.operand %[[INDEX_54]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "emit_stream" %[[OPERAND_51]]
// CHECK:         %[[INDEX_55:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_52:.*]] = dxsa.operand %[[INDEX_55]] {num_components = 0 : i32, type = 16 : i32}
// CHECK:         dxsa.instruction "cut_stream" %[[OPERAND_52]]
// CHECK:         dxsa.instruction "ret"

