// RUN: mlir-translate --import-dxsa-bin %S/inputs/hs2.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.instruction "hs_decls"
// CHECK:         dxsa.dcl_input_control_point_count 32
// CHECK:         dxsa.dcl_output_control_point_count 16
// CHECK:         dxsa.dcl_tessellator_domain  domain_quad
// CHECK:         dxsa.dcl_tessellator_partitioning  partitioning_fractional_odd
// CHECK:         dxsa.dcl_tessellator_output_primitive  output_triangle_cw
// CHECK:         dxsa.dcl_hs_max_tessfactor 3.000000e+00
// CHECK:         dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.instruction "hs_control_point_phase"
// CHECK:         dxsa.dcl_input <type = output_control_point_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input_primitive_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input, components = 4, mask = <x, y, z, w>, index = [32, 0]>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand  {num_components = 1 : i32, type = 22 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_0]], %[[OPERAND_1]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_1]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand  {num_components = 1 : i32, type = 11 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_2]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.rel %[[OPERAND_5]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_4]], %[[INDEX_5]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_6]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.rel %[[OPERAND_7]]
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_7]], %[[INDEX_8]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_4]], %[[OPERAND_6]], %[[OPERAND_8]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         dxsa.instruction "hs_fork_phase"
// CHECK:         dxsa.dcl_hs_fork_phase_instance_count 4
// CHECK:         dxsa.dcl_input <type = input_primitive_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input_fork_instance_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input_control_point, components = 4, mask = <y>, index = [32, 0]>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x>, index = [0]>, <finalQuadUeq0EdgeTessFactor>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x>, index = [1]>, <finalQuadVeq0EdgeTessFactor>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x>, index = [2]>, <finalQuadUeq1EdgeTessFactor>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x>, index = [3]>, <finalQuadVeq1EdgeTessFactor>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_index_range <type = output, components = 4, mask = <x>, index = [0]>, 4
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand  {num_components = 1 : i32, type = 11 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_9]], %[[OPERAND_10]]
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_10]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand.imm {imm = dense<1077936128> : vector<1xi32>}
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_11]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.rel %[[OPERAND_13]]
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_12]], %[[INDEX_13]] {num_components = 4 : i32, one = 1 : i32, type = 25 : i32}
// CHECK:         dxsa.instruction "min" %[[OPERAND_11]], %[[OPERAND_12]], %[[OPERAND_14]]
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_14]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand  {num_components = 4 : i32, one = 0 : i32, type = 23 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_15]], %[[OPERAND_16]]
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.rel %[[OPERAND_17]]
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_16]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_17]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_18]], %[[OPERAND_19]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         dxsa.instruction "hs_fork_phase"
// CHECK:         dxsa.dcl_input <type = input_primitive_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input_control_point, components = 4, mask = <x, y>, index = [32, 0]>
// CHECK:         dxsa.dcl_input <type = output_control_point, components = 4, mask = <x>, index = [16, 0]>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [6]>
// CHECK:         dxsa.dcl_temps 3
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_18]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_20]], %[[OPERAND_21]]
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_19]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand.imm {imm = dense<0> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_22]], %[[OPERAND_23]]
// CHECK:         dxsa.instruction "loop"
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_20]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_21]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand.imm {imm = dense<32> : vector<1xi32>}
// CHECK:         dxsa.instruction "ige" %[[OPERAND_24]], %[[OPERAND_25]], %[[OPERAND_26]]
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_22]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "breakc" %[[OPERAND_27]]
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_23]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand  {num_components = 1 : i32, type = 11 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_28]], %[[OPERAND_29]]
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_24]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_25]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.rel %[[OPERAND_31]]
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_26]], %[[INDEX_27]] {num_components = 4 : i32, one = 0 : i32, type = 25 : i32}
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand %[[INDEX_28]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.rel %[[OPERAND_33]]
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_34:.*]] = dxsa.operand %[[INDEX_29]], %[[INDEX_30]] {num_components = 4 : i32, one = 1 : i32, type = 25 : i32}
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_35:.*]] = dxsa.operand %[[INDEX_31]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.rel %[[OPERAND_35]]
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_36:.*]] = dxsa.operand %[[INDEX_32]], %[[INDEX_33]] {num_components = 4 : i32, one = 1 : i32, type = 25 : i32}
// CHECK:         dxsa.instruction "mad" %[[OPERAND_30]], %[[OPERAND_32]], %[[OPERAND_34]], %[[OPERAND_36]]
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_37:.*]] = dxsa.operand %[[INDEX_34]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_38:.*]] = dxsa.operand %[[INDEX_35]] {num_components = 4 : i32, swizzle = dense<1> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_39:.*]] = dxsa.operand %[[INDEX_36]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_37]], %[[OPERAND_38]], %[[OPERAND_39]]
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_40:.*]] = dxsa.operand %[[INDEX_37]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_38:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_41:.*]] = dxsa.operand %[[INDEX_38]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_42:.*]] = dxsa.operand.imm {imm = dense<1> : vector<1xi32>}
// CHECK:         dxsa.instruction "ushr" %[[OPERAND_40]], %[[OPERAND_41]], %[[OPERAND_42]]
// CHECK:         %[[INDEX_39:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_43:.*]] = dxsa.operand %[[INDEX_39]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_40:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_44:.*]] = dxsa.operand %[[INDEX_40]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_41:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_45:.*]] = dxsa.operand %[[INDEX_41]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_42:.*]] = dxsa.index.rel %[[OPERAND_45]]
// CHECK:         %[[INDEX_43:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_46:.*]] = dxsa.operand %[[INDEX_42]], %[[INDEX_43]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 26 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_43]], %[[OPERAND_44]], %[[OPERAND_46]]
// CHECK:         %[[INDEX_44:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_47:.*]] = dxsa.operand %[[INDEX_44]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_45:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_48:.*]] = dxsa.operand %[[INDEX_45]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_49:.*]] = dxsa.operand.imm {imm = dense<1> : vector<1xi32>}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_47]], %[[OPERAND_48]], %[[OPERAND_49]]
// CHECK:         dxsa.instruction "endloop"
// CHECK:         %[[INDEX_46:.*]] = dxsa.index.imm {imm = 6 : i32}
// CHECK:         %[[OPERAND_50:.*]] = dxsa.operand %[[INDEX_46]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_47:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_51:.*]] = dxsa.operand %[[INDEX_47]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_50]], %[[OPERAND_51]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         dxsa.instruction "hs_join_phase"
// CHECK:         dxsa.dcl_hs_join_phase_instance_count 2
// CHECK:         dxsa.dcl_input <type = input_patch_constant, components = 4, mask = <x>, index = [6]>
// CHECK:         dxsa.dcl_input <type = input_primitive_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input_join_instance_id, components = 0>
// CHECK:         dxsa.dcl_input <type = input_control_point, components = 4, mask = <w>, index = [32, 0]>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x>, index = [4]>, <finalQuadUInsideTessFactor>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x>, index = [5]>, <finalQuadVInsideTessFactor>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_index_range <type = output, components = 4, mask = <x>, index = [4]>, 2
// CHECK:         %[[INDEX_48:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_52:.*]] = dxsa.operand %[[INDEX_48]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_53:.*]] = dxsa.operand  {num_components = 1 : i32, type = 11 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_52]], %[[OPERAND_53]]
// CHECK:         %[[INDEX_49:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_54:.*]] = dxsa.operand %[[INDEX_49]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_50:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_55:.*]] = dxsa.operand %[[INDEX_50]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_51:.*]] = dxsa.index.rel %[[OPERAND_55]]
// CHECK:         %[[INDEX_52:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_56:.*]] = dxsa.operand %[[INDEX_51]], %[[INDEX_52]] {num_components = 4 : i32, one = 3 : i32, type = 25 : i32}
// CHECK:         %[[INDEX_53:.*]] = dxsa.index.imm {imm = 6 : i32}
// CHECK:         %[[OPERAND_57:.*]] = dxsa.operand %[[INDEX_53]] {num_components = 4 : i32, one = 0 : i32, type = 27 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_54]], %[[OPERAND_56]], %[[OPERAND_57]]
// CHECK:         %[[INDEX_54:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_58:.*]] = dxsa.operand %[[INDEX_54]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_55:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_59:.*]] = dxsa.operand %[[INDEX_55]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_60:.*]] = dxsa.operand.imm {imm = dense<1077936128> : vector<1xi32>}
// CHECK:         dxsa.instruction "min" %[[OPERAND_58]], %[[OPERAND_59]], %[[OPERAND_60]]
// CHECK:         %[[INDEX_56:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_61:.*]] = dxsa.operand %[[INDEX_56]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_62:.*]] = dxsa.operand  {num_components = 4 : i32, one = 0 : i32, type = 24 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_61]], %[[OPERAND_62]]
// CHECK:         %[[INDEX_57:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_63:.*]] = dxsa.operand %[[INDEX_57]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_58:.*]] = dxsa.index.rel.imm %[[OPERAND_63]] {imm = 4 : i32, op = "add"}
// CHECK:         %[[OPERAND_64:.*]] = dxsa.operand %[[INDEX_58]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_59:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_65:.*]] = dxsa.operand %[[INDEX_59]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_64]], %[[OPERAND_65]]
// CHECK:         dxsa.instruction "ret"

