// RUN: mlir-translate --import-dxsa-bin %S/inputs/indexableinput2.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_1]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_2]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_3]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_4]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_5]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_5]]
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 6 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_6]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 7 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_7]]
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 8 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_8]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_8]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 9 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_9]]
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 10 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_10]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_sgv %[[OPERAND_10]], <sampleIndex>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_index_range <type = input, components = 4, mask = <x, y>, index = [0]>, 3
// CHECK:         dxsa.dcl_index_range <type = input, components = 4, mask = <x>, index = [3]>, 6
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_11]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 10 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_13]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_14]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.rel %[[OPERAND_14]]
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_16]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_13]], %[[OPERAND_15]], %[[OPERAND_16]]
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_17]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 9 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_18]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_17]], %[[OPERAND_18]]
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_19]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_20]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_21]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.rel.imm %[[OPERAND_21]] {imm = 3 : i32, op = "add"}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_22]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_19]], %[[OPERAND_20]], %[[OPERAND_22]]
// CHECK:         dxsa.instruction "ret"

