// RUN: mlir-translate --import-dxsa-bin %S/inputs/indexabletemp1.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 14>, <dynamicIndexed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 32 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_indexable_temp x0[6], 4
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]], %[[INDEX_5]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.rel %[[OPERAND_5]]
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]], %[[INDEX_8]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_4]], %[[OPERAND_6]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_9]], %[[INDEX_10]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.rel.imm %[[OPERAND_8]] {imm = 6 : i32, op = "add"}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_11]], %[[INDEX_13]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_7]], %[[OPERAND_9]]
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_14]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 1 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand.imm {imm = dense<[2, 3, 4, 5]> : vector<4xi32>}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_10]], %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_16]], %[[INDEX_17]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_19]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.rel %[[OPERAND_14]]
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_18]], %[[INDEX_20]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_13]], %[[OPERAND_15]]
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_21]], %[[INDEX_22]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_24]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.rel %[[OPERAND_17]]
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_23]], %[[INDEX_25]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_16]], %[[OPERAND_18]]
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_26]], %[[INDEX_27]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_29]] {num_components = 4 : i32, one = 2 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.rel %[[OPERAND_20]]
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_28]], %[[INDEX_30]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_19]], %[[OPERAND_21]]
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_31]], %[[INDEX_32]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_34]] {num_components = 4 : i32, one = 3 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.rel %[[OPERAND_23]]
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_33]], %[[INDEX_35]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_22]], %[[OPERAND_24]]
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_36]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand %[[INDEX_37]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         %[[INDEX_38:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_38]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_25]], %[[OPERAND_26]], %[[OPERAND_27]]
// CHECK:         %[[INDEX_39:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_39]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_40:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_41:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_41]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_42:.*]] = dxsa.index.rel %[[OPERAND_29]]
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_40]], %[[INDEX_42]] {num_components = 4 : i32, one = 0 : i32, type = 3 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_28]], %[[OPERAND_30]]
// CHECK:         dxsa.instruction "ret"

