// RUN: mlir-translate --import-dxsa-bin %S/inputs/input2.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed|enableMinimumPrecision>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_2]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 240 : i32, min_precision = 1 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_3]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_siv  linear %[[OPERAND_4]], <clipDistance>
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_5]] {mask = 32 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_siv  linear %[[OPERAND_5]], <cullDistance>
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_6]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {mask = 32 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_sgv %[[OPERAND_7]], <primitiveID>
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_8]] {mask = 64 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_siv  constant %[[OPERAND_8]], <renderTargetArrayIndex>
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {mask = 128 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_siv  constant %[[OPERAND_9]], <viewportArrayIndex>
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 6 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_10]] {mask = 240 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_siv  linearNoPerspective %[[OPERAND_10]], <position>
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 7 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_11]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_sgv %[[OPERAND_11]], <sampleIndex>
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 7 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_12]] {mask = 32 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps_sgv %[[OPERAND_12]], <isFrontFace>
// CHECK:         dxsa.dcl_input <type = inner_coverage, components = 1>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 2
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_13]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_14]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "itof" %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_15]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_16]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_17]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_15]], %[[OPERAND_16]], %[[OPERAND_17]]
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_18]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_19]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_18]], %[[OPERAND_19]]
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_20]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_21]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_22]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_20]], %[[OPERAND_21]], %[[OPERAND_22]]
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_23]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_24]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 3 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_25]] {min_precision = 1 : i32, num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_23]], %[[OPERAND_24]], %[[OPERAND_25]]
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand %[[INDEX_26]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_27:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_27]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_28:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_28]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_26]], %[[OPERAND_27]], %[[OPERAND_28]]
// CHECK:         %[[INDEX_29:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_29:.*]] = dxsa.operand %[[INDEX_29]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_30:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_30:.*]] = dxsa.operand %[[INDEX_30]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_31:.*]] = dxsa.index.imm {imm = 4 : i32}
// CHECK:         %[[OPERAND_31:.*]] = dxsa.operand %[[INDEX_31]] {num_components = 4 : i32, swizzle = dense<1> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_29]], %[[OPERAND_30]], %[[OPERAND_31]]
// CHECK:         %[[INDEX_32:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_32:.*]] = dxsa.operand %[[INDEX_32]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_33:.*]] = dxsa.operand  {num_components = 4 : i32, one = 0 : i32, type = 42 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_32]], %[[OPERAND_33]]
// CHECK:         %[[INDEX_33:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_34:.*]] = dxsa.operand %[[INDEX_33]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_34:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_35:.*]] = dxsa.operand %[[INDEX_34]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_35:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_36:.*]] = dxsa.operand %[[INDEX_35]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_34]], %[[OPERAND_35]], %[[OPERAND_36]]
// CHECK:         %[[INDEX_36:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_37:.*]] = dxsa.operand %[[INDEX_36]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_37:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_38:.*]] = dxsa.operand %[[INDEX_37]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_37]], %[[OPERAND_38]]
// CHECK:         %[[INDEX_38:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_39:.*]] = dxsa.operand %[[INDEX_38]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_39:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_40:.*]] = dxsa.operand %[[INDEX_39]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_40:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_41:.*]] = dxsa.operand %[[INDEX_40]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_39]], %[[OPERAND_40]], %[[OPERAND_41]]
// CHECK:         %[[INDEX_41:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_42:.*]] = dxsa.operand %[[INDEX_41]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_42:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_43:.*]] = dxsa.operand %[[INDEX_42]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_42]], %[[OPERAND_43]]
// CHECK:         %[[INDEX_43:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_44:.*]] = dxsa.operand %[[INDEX_43]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_44:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_45:.*]] = dxsa.operand %[[INDEX_44]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_45:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_46:.*]] = dxsa.operand %[[INDEX_45]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_44]], %[[OPERAND_45]], %[[OPERAND_46]]
// CHECK:         %[[INDEX_46:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_47:.*]] = dxsa.operand %[[INDEX_46]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_47:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_48:.*]] = dxsa.operand %[[INDEX_47]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_47]], %[[OPERAND_48]]
// CHECK:         %[[INDEX_48:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_49:.*]] = dxsa.operand %[[INDEX_48]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_49:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_50:.*]] = dxsa.operand %[[INDEX_49]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_50:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_51:.*]] = dxsa.operand %[[INDEX_50]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_49]], %[[OPERAND_50]], %[[OPERAND_51]]
// CHECK:         %[[INDEX_51:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_52:.*]] = dxsa.operand %[[INDEX_51]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_52:.*]] = dxsa.index.imm {imm = 5 : i32}
// CHECK:         %[[OPERAND_53:.*]] = dxsa.operand %[[INDEX_52]] {num_components = 4 : i32, one = 3 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_52]], %[[OPERAND_53]]
// CHECK:         %[[INDEX_53:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_54:.*]] = dxsa.operand %[[INDEX_53]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_54:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_55:.*]] = dxsa.operand %[[INDEX_54]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_55:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_56:.*]] = dxsa.operand %[[INDEX_55]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_54]], %[[OPERAND_55]], %[[OPERAND_56]]
// CHECK:         %[[INDEX_56:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_57:.*]] = dxsa.operand %[[INDEX_56]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_57:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_58:.*]] = dxsa.operand %[[INDEX_57]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_58:.*]] = dxsa.index.imm {imm = 6 : i32}
// CHECK:         %[[OPERAND_59:.*]] = dxsa.operand %[[INDEX_58]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_57]], %[[OPERAND_58]], %[[OPERAND_59]]
// CHECK:         %[[INDEX_59:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_60:.*]] = dxsa.operand %[[INDEX_59]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_60:.*]] = dxsa.index.imm {imm = 7 : i32}
// CHECK:         %[[OPERAND_61:.*]] = dxsa.operand %[[INDEX_60]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "utof" %[[OPERAND_60]], %[[OPERAND_61]]
// CHECK:         %[[INDEX_61:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_62:.*]] = dxsa.operand %[[INDEX_61]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_62:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_63:.*]] = dxsa.operand %[[INDEX_62]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_63:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_64:.*]] = dxsa.operand %[[INDEX_63]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_62]], %[[OPERAND_63]], %[[OPERAND_64]]
// CHECK:         %[[INDEX_64:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_65:.*]] = dxsa.operand %[[INDEX_64]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_65:.*]] = dxsa.index.imm {imm = 7 : i32}
// CHECK:         %[[OPERAND_66:.*]] = dxsa.operand %[[INDEX_65]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         %[[OPERAND_67:.*]] = dxsa.operand.imm {imm = dense<1065353216> : vector<1xi32>}
// CHECK:         dxsa.instruction "and" %[[OPERAND_65]], %[[OPERAND_66]], %[[OPERAND_67]]
// CHECK:         %[[INDEX_66:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_68:.*]] = dxsa.operand %[[INDEX_66]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_67:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_69:.*]] = dxsa.operand %[[INDEX_67]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_68:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_70:.*]] = dxsa.operand %[[INDEX_68]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_68]], %[[OPERAND_69]], %[[OPERAND_70]]
// CHECK:         dxsa.instruction "ret"

