// RUN: mlir-translate --import-dxsa-bin %S/inputs/minprec6.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed|enableMinimumPrecision>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 1>, <immediateIndexed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, min_precision = 4 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 2
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 16 : i32, min_precision = 4 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {min_precision = 4 : i32, num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand.imm {imm = dense<2> : vector<1xi32>}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_1]], %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_3]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_4]] {min_precision = 4 : i32, num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_5]], %[[INDEX_6]] {min_precision = 4 : i32, num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "ieq" %[[OPERAND_4]], %[[OPERAND_5]], %[[OPERAND_6]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "if" %[[OPERAND_7]]
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_8]] {mask = 16 : i32, min_precision = 4 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {min_precision = 4 : i32, num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand.imm {imm = dense<-1> : vector<1xi32>}
// CHECK:         dxsa.instruction "iadd" %[[OPERAND_8]], %[[OPERAND_9]], %[[OPERAND_10]]
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_10]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_11]] {min_precision = 4 : i32, num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_11]], %[[OPERAND_12]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         dxsa.instruction "else"
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_12]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand.imm {imm = dense<1> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         dxsa.instruction "endif"
// CHECK:         dxsa.instruction "ret"

