// RUN: mlir-translate --import-dxsa-bin %S/inputs/samplecount.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 48 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand  {num_components = 4 : i32, one = 0 : i32, type = 14 : i32}
// CHECK:         dxsa.instruction "sampleinfo" %[[OPERAND_0]], %[[OPERAND_1]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_1]] {mask = 192 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         dxsa.instruction "ret"

