// RUN: mlir-translate --import-dxsa-bin %S/inputs/sincos.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_input <type = input, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_output_siv <type = output, components = 4, mask = <x, y, z, w>, index = [0]>, <position>
// CHECK:         dxsa.dcl_temps 3
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_0]], %[[OPERAND_1]], %[[OPERAND_2]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand  {num_components = 0 : i32, type = 13 : i32}
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_4]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "sincos" %[[OPERAND_3]], %[[OPERAND_4]], %[[OPERAND_5]]
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_5]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_6]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "sincos" %[[OPERAND_6]], %[[OPERAND_7]], %[[OPERAND_8]]
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_8]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_9]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_10]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_9]], %[[OPERAND_10]], %[[OPERAND_11]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_11]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 0 : i32}
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_13]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "add" %[[OPERAND_12]], %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         dxsa.instruction "ret"

