// RUN: mlir-translate --import-dxsa-bin %S/inputs/sub1.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 1>, <immediateIndexed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_0]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_indexable_temp x0[8], 4
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]], %[[INDEX_2]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "switch" %[[OPERAND_1]]
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand.imm {imm = dense<0> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_2]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "call" %[[OPERAND_3]]
// CHECK:         dxsa.instruction "break"
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand.imm {imm = dense<1> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_4]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_4]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "call" %[[OPERAND_5]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "default"
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_5]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "call" %[[OPERAND_6]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "endswitch"
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_6]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_7]], %[[INDEX_8]] {num_components = 4 : i32, one = 1 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_7]], %[[OPERAND_8]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_9]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_11]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.rel %[[OPERAND_10]]
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_10]], %[[INDEX_12]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 3 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_9]], %[[OPERAND_11]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_13]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "label" %[[OPERAND_12]]
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_14]], %[[INDEX_15]] {mask = 240 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand.imm {imm = dense<1082130432> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_16]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "label" %[[OPERAND_15]]
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_17]], %[[INDEX_18]] {mask = 240 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_19]] {num_components = 4 : i32, swizzle = dense<0> : vector<4xi32>, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_16]], %[[OPERAND_17]]
// CHECK:         dxsa.instruction "ret"
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 2 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_20]] {num_components = 0 : i32, type = 10 : i32}
// CHECK:         dxsa.instruction "label" %[[OPERAND_18]]
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand %[[INDEX_21]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_22]], %[[INDEX_23]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_19]], %[[OPERAND_20]]
// CHECK:         %[[INDEX_24:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_25:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_25]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_26:.*]] = dxsa.index.rel %[[OPERAND_21]]
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand %[[INDEX_24]], %[[INDEX_26]] {mask = 240 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand.imm {imm = dense<0> : vector<4xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_22]], %[[OPERAND_23]]
// CHECK:         dxsa.instruction "ret"

