// RUN: mlir-translate --import-dxsa-bin %S/inputs/switch3.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 48 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  linear %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 112 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "switch" %[[OPERAND_2]]
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand.imm {imm = dense<1> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_3]]
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "switch" %[[OPERAND_4]]
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand.imm {imm = dense<20> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_5]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_4]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_5]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand.imm {imm = dense<30> : vector<1xi32>}
// CHECK:         dxsa.instruction "ieq" %[[OPERAND_6]], %[[OPERAND_7]], %[[OPERAND_8]]
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_6]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "if" %[[OPERAND_9]]
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_7]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand.imm {imm = dense<1085276160> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_10]], %[[OPERAND_11]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "endif"
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_8]] {mask = 32 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_9]] {num_components = 4 : i32, one = 2 : i32, type = 1 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand.imm {imm = dense<31> : vector<1xi32>}
// CHECK:         dxsa.instruction "ieq" %[[OPERAND_12]], %[[OPERAND_13]], %[[OPERAND_14]]
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_10]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand.imm {imm = dense<1085695590> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_15]], %[[OPERAND_16]]
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_17:.*]] = dxsa.operand %[[INDEX_11]] {num_components = 4 : i32, one = 1 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "breakc" %[[OPERAND_17]]
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_18:.*]] = dxsa.operand %[[INDEX_12]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_19:.*]] = dxsa.operand.imm {imm = dense<1085905306> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_18]], %[[OPERAND_19]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "default"
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_20:.*]] = dxsa.operand %[[INDEX_13]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_21:.*]] = dxsa.operand %[[INDEX_14]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_20]], %[[OPERAND_21]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "endswitch"
// CHECK:         dxsa.instruction "break"
// CHECK:         %[[OPERAND_22:.*]] = dxsa.operand.imm {imm = dense<2> : vector<1xi32>}
// CHECK:         dxsa.instruction "case" %[[OPERAND_22]]
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_23:.*]] = dxsa.operand %[[INDEX_15]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_24:.*]] = dxsa.operand %[[INDEX_16]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_23]], %[[OPERAND_24]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "default"
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_25:.*]] = dxsa.operand %[[INDEX_17]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_26:.*]] = dxsa.operand.imm {imm = dense<1077936128> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_25]], %[[OPERAND_26]]
// CHECK:         dxsa.instruction "break"
// CHECK:         dxsa.instruction "endswitch"
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_27:.*]] = dxsa.operand %[[INDEX_18]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_28:.*]] = dxsa.operand %[[INDEX_19]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_27]], %[[OPERAND_28]]
// CHECK:         dxsa.instruction "ret"

