// RUN: mlir-translate --import-dxsa-bin %S/inputs/cyclecounter.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x, y, z, w>, index = [0]>
// CHECK:         dxsa.dcl_input <type = cycle_counter, components = 4, mask = <x>>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 240 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand.imm {imm = dense<0> : vector<1xi32>}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_0]], %[[OPERAND_1]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_1]] {mask = 64 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand  {num_components = 4 : i32, one = 0 : i32, type = 40 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_2]] {mask = 240 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 4 : i32, swizzle = dense<[0, 1, 2, 3]> : vector<4xi32>, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_4]], %[[OPERAND_5]]

