// RUN: mlir-translate --import-dxsa-bin %S/inputs/indexabletemp4.bin | FileCheck %s
// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py

// CHECK-LABEL:   dxsa.dcl_global_flags <refactoringAllowed>
// CHECK:         dxsa.dcl_constant_buffer <id = 0, size = 12>, <dynamicIndexed>
// CHECK:         %[[INDEX_0:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_0:.*]] = dxsa.operand %[[INDEX_0]] {mask = 16 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_0]]
// CHECK:         %[[INDEX_1:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_1:.*]] = dxsa.operand %[[INDEX_1]] {mask = 32 : i32, num_components = 4 : i32, type = 1 : i32}
// CHECK:         dxsa.dcl_input_ps  constant %[[OPERAND_1]]
// CHECK:         dxsa.dcl_output <type = output, components = 4, mask = <x>, index = [0]>
// CHECK:         dxsa.dcl_temps 1
// CHECK:         dxsa.dcl_indexable_temp x0[4], 2
// CHECK:         %[[INDEX_2:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_2:.*]] = dxsa.operand %[[INDEX_2]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_3:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_3:.*]] = dxsa.operand %[[INDEX_3]] {num_components = 4 : i32, one = 0 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_2]], %[[OPERAND_3]]
// CHECK:         %[[INDEX_4:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_5:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_4:.*]] = dxsa.operand %[[INDEX_4]], %[[INDEX_5]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_6:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_7:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_5:.*]] = dxsa.operand %[[INDEX_7]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_8:.*]] = dxsa.index.rel %[[OPERAND_5]]
// CHECK:         %[[OPERAND_6:.*]] = dxsa.operand %[[INDEX_6]], %[[INDEX_8]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_4]], %[[OPERAND_6]]
// CHECK:         %[[INDEX_9:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_10:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_7:.*]] = dxsa.operand %[[INDEX_9]], %[[INDEX_10]] {mask = 16 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_11:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_12:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_8:.*]] = dxsa.operand %[[INDEX_12]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_13:.*]] = dxsa.index.rel.imm %[[OPERAND_8]] {imm = 4 : i32, op = "add"}
// CHECK:         %[[OPERAND_9:.*]] = dxsa.operand %[[INDEX_11]], %[[INDEX_13]] {num_components = 4 : i32, one = 0 : i32, type = 8 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_7]], %[[OPERAND_9]]
// CHECK:         %[[INDEX_14:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_10:.*]] = dxsa.operand %[[INDEX_14]] {mask = 16 : i32, num_components = 4 : i32, type = 0 : i32}
// CHECK:         %[[INDEX_15:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_11:.*]] = dxsa.operand %[[INDEX_15]] {num_components = 4 : i32, one = 1 : i32, type = 1 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_10]], %[[OPERAND_11]]
// CHECK:         %[[INDEX_16:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_17:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_12:.*]] = dxsa.operand %[[INDEX_16]], %[[INDEX_17]] {mask = 32 : i32, num_components = 4 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_18:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_13:.*]] = dxsa.operand %[[INDEX_18]] {num_components = 4 : i32, one = 0 : i32, type = 0 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_12]], %[[OPERAND_13]]
// CHECK:         %[[INDEX_19:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[OPERAND_14:.*]] = dxsa.operand %[[INDEX_19]] {mask = 16 : i32, num_components = 4 : i32, type = 2 : i32}
// CHECK:         %[[INDEX_20:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_21:.*]] = dxsa.index.imm {imm = 0 : i32}
// CHECK:         %[[INDEX_22:.*]] = dxsa.index.imm {imm = 1 : i32}
// CHECK:         %[[OPERAND_15:.*]] = dxsa.operand %[[INDEX_21]], %[[INDEX_22]] {num_components = 4 : i32, one = 1 : i32, type = 3 : i32}
// CHECK:         %[[INDEX_23:.*]] = dxsa.index.rel.imm %[[OPERAND_15]] {imm = 77 : i32, op = "add"}
// CHECK:         %[[OPERAND_16:.*]] = dxsa.operand %[[INDEX_20]], %[[INDEX_23]] {num_components = 4 : i32, one = 0 : i32, type = 3 : i32}
// CHECK:         dxsa.instruction "mov" %[[OPERAND_14]], %[[OPERAND_16]]
// CHECK:         dxsa.instruction "ret"

