#!/bin/sh -e

generate_header() {
  echo "//===-- libcall-set-defaults.inc ------------------------------------------===//"
  echo "//"
  echo "// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions."
  echo "// See https://llvm.org/LICENSE.txt for license information."
  echo "// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception"
  echo "//"
  echo "//===----------------------------------------------------------------------===//"
  echo "//"
  echo "// This file is not part of the interface of this library."
  echo "//"
  echo "// The particular target implementation can define some macroses customizing"
  echo "// target-specific aliases, calling conventions, etc. After that, this file"
  echo "// sets the default values for everything not yet set."
  echo "//"
  echo "// DO NOT EDIT! This file was auto-generated by generate_builtins_macro.sh"
  echo "//"
  echo "//===----------------------------------------------------------------------===//"
  echo
}

generate_macroses() {
  prefix=$1
  shift

  for libcall in $*
  do
    echo "#ifndef ${prefix}${libcall}"
    echo "#define ${prefix}${libcall}"
    echo "#endif"
  done
}

generate_file() {
  generate_header
  echo "#ifndef LIBCALL_DEFAULTS"
  echo "#define LIBCALL_DEFAULTS"
  echo
  echo "// Special LibCall attributes, empty by default"
  generate_macroses ATTR "$*"
  echo
  echo "// Misc auxiliary declarations to place at the end of source file"
  generate_macroses AUX_DECLS "$*"
  echo
  echo "#endif // LIBCALL_DEFAULTS"
}

libcalls="
__absvdi2
__absvsi2
__absvti2
__adddf3
__addsf3
__addtf3
__addvdi3
__addvsi3
__addvti3
__aeabi_lcmp
__aeabi_ulcmp
__ashldi3
__ashlti3
__ashrdi3
__ashrti3
__bswapdi2
__bswapsi2
__clzdi2
__clzsi2
__clzti2
__cmpdi2
__cmpti2
__ctzdi2
__ctzsi2
__ctzti2
__divdc3
__divdf3
__divdi3
__divmoddi4
__divmodsi4
__divsc3
__divsf3
__divsi3
__divtc3
__divtf3
__divti3
__divxc3
__dtoi64
__dtou64
__enable_execute_stack
__eprintf
__extenddftf2
__extendhfsf2
__extendsfdf2
__extendsftf2
__ffsdi2
__ffssi2
__ffsti2
__fixdfdi
__fixdfsi
__fixdfti
__fixsfdi
__fixsfsi
__fixsfti
__fixtfdi
__fixtfsi
__fixtfti
__fixunsdfdi
__fixunsdfsi
__fixunsdfti
__fixunssfdi
__fixunssfsi
__fixunssfti
__fixunstfdi
__fixunstfsi
__fixunstfti
__fixunsxfdi
__fixunsxfsi
__fixunsxfti
__fixxfdi
__fixxfti
__floatdidf
__floatdisf
__floatditf
__floatdixf
__floatsidf
__floatsisf
__floatsitf
__floattidf
__floattisf
__floattitf
__floattixf
__floatundidf
__floatundisf
__floatunditf
__floatundixf
__floatunsidf
__floatunsisf
__floatunsitf
__floatuntidf
__floatuntisf
__floatuntitf
__floatuntixf
__gcc_personality_sj0
__gcc_personality_v0
__gedf2
__gesf2
__getf2
__gnu_f2h_ieee
__gnu_h2f_ieee
__i64tod
__i64tos
__ledf2
__lesf2
__letf2
__lshrdi3
__lshrti3
__moddi3
__modsi3
__modti3
__muldc3
__muldf3
__muldi3
__mulodi4
__mulosi4
__muloti4
__mulsc3
__mulsf3
__multc3
__multf3
__multi3
__mulvdi3
__mulvsi3
__mulvti3
__mulxc3
__negdf2
__negdi2
__negsf2
__negti2
__negvdi2
__negvsi2
__negvti2
__paritydi2
__paritysi2
__parityti2
__popcountdi2
__popcountsi2
__popcountti2
__powidf2
__powisf2
__powitf2
__powixf2
__stoi64
__stou64
__subdf3
__subsf3
__subtf3
__subvdi3
__subvsi3
__subvti3
__trampoline_setup
__truncdfhf2
__truncdfsf2
__truncsfhf2
__trunctfdf2
__trunctfsf2
__u64tod
__u64tos
__ucmpdi2
__ucmpti2
__udivdi3
__udivmoddi4
__udivmodsi4
__udivmodti4
__udivsi3
__udivti3
__umoddi3
__umodsi3
__umodti3
__unordsf2
__unorddf2
__unordtf2
"

generate_file $libcalls
