; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py
; RUN: llc -verify-machineinstrs -o - -mtriple=aarch64-none-linux-gnu -mattr=+pauth -code-model=tiny < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -o - -mtriple=aarch64-none-linux-gnu -mattr=+pauth -code-model=tiny -fast-isel < %s | FileCheck %s
; RUN: llc -verify-machineinstrs -o - -mtriple=aarch64-none-linux-gnu -mattr=+pauth -code-model=tiny -global-isel < %s | FileCheck %s --check-prefix=CHECK-GLOBISEL

; Note fast-isel tests here will fall back to isel

@src = external local_unnamed_addr global [65536 x i8], align 1
@dst = external global [65536 x i8], align 1
@ptr = external local_unnamed_addr global ptr, align 8

define dso_local void @foo1() {
; CHECK-LABEL: foo1:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    adr x16, :got_auth:src
; CHECK-NEXT:    ldr x8, [x16]
; CHECK-NEXT:    autda x8, x16
; CHECK-NEXT:    adr x16, :got_auth:dst
; CHECK-NEXT:    ldrb w8, [x8]
; CHECK-NEXT:    ldr x9, [x16]
; CHECK-NEXT:    autda x9, x16
; CHECK-NEXT:    strb w8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-GLOBISEL-LABEL: foo1:
; CHECK-GLOBISEL:       // %bb.0: // %entry
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:src
; CHECK-GLOBISEL-NEXT:    ldr x8, [x16]
; CHECK-GLOBISEL-NEXT:    autda x8, x16
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:dst
; CHECK-GLOBISEL-NEXT:    ldrb w8, [x8]
; CHECK-GLOBISEL-NEXT:    ldr x9, [x16]
; CHECK-GLOBISEL-NEXT:    autda x9, x16
; CHECK-GLOBISEL-NEXT:    strb w8, [x9]
; CHECK-GLOBISEL-NEXT:    ret
entry:
  %0 = load i8, ptr @src, align 1
  store i8 %0, ptr @dst, align 1
  ret void
}

define dso_local void @foo2() {
; CHECK-LABEL: foo2:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    adr x16, :got_auth:ptr
; CHECK-NEXT:    ldr x8, [x16]
; CHECK-NEXT:    autda x8, x16
; CHECK-NEXT:    adr x16, :got_auth:dst
; CHECK-NEXT:    ldr x9, [x16]
; CHECK-NEXT:    autda x9, x16
; CHECK-NEXT:    str x9, [x8]
; CHECK-NEXT:    ret
;
; CHECK-GLOBISEL-LABEL: foo2:
; CHECK-GLOBISEL:       // %bb.0: // %entry
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:ptr
; CHECK-GLOBISEL-NEXT:    ldr x8, [x16]
; CHECK-GLOBISEL-NEXT:    autda x8, x16
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:dst
; CHECK-GLOBISEL-NEXT:    ldr x9, [x16]
; CHECK-GLOBISEL-NEXT:    autda x9, x16
; CHECK-GLOBISEL-NEXT:    str x9, [x8]
; CHECK-GLOBISEL-NEXT:    ret
entry:
  store ptr @dst, ptr @ptr, align 8
  ret void
}

define dso_local void @foo3() {
; FIXME: Needn't adr ptr
;
; CHECK-LABEL: foo3:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    adr x16, :got_auth:src
; CHECK-NEXT:    ldr x8, [x16]
; CHECK-NEXT:    autda x8, x16
; CHECK-NEXT:    adr x16, :got_auth:ptr
; CHECK-NEXT:    ldrb w8, [x8]
; CHECK-NEXT:    ldr x9, [x16]
; CHECK-NEXT:    autda x9, x16
; CHECK-NEXT:    ldr x9, [x9]
; CHECK-NEXT:    strb w8, [x9]
; CHECK-NEXT:    ret
;
; CHECK-GLOBISEL-LABEL: foo3:
; CHECK-GLOBISEL:       // %bb.0: // %entry
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:src
; CHECK-GLOBISEL-NEXT:    ldr x8, [x16]
; CHECK-GLOBISEL-NEXT:    autda x8, x16
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:ptr
; CHECK-GLOBISEL-NEXT:    ldrb w8, [x8]
; CHECK-GLOBISEL-NEXT:    ldr x9, [x16]
; CHECK-GLOBISEL-NEXT:    autda x9, x16
; CHECK-GLOBISEL-NEXT:    ldr x9, [x9]
; CHECK-GLOBISEL-NEXT:    strb w8, [x9]
; CHECK-GLOBISEL-NEXT:    ret
entry:
  %0 = load i8, ptr @src, align 1
  %1 = load ptr, ptr @ptr, align 8
  store i8 %0, ptr %1, align 1
  ret void
}

declare void @func(...)

define dso_local ptr @externfuncaddr() {
; CHECK-LABEL: externfuncaddr:
; CHECK:       // %bb.0: // %entry
; CHECK-NEXT:    adr x16, :got_auth:func
; CHECK-NEXT:    ldr x0, [x16]
; CHECK-NEXT:    autia x0, x16
; CHECK-NEXT:    ret
;
; CHECK-GLOBISEL-LABEL: externfuncaddr:
; CHECK-GLOBISEL:       // %bb.0: // %entry
; CHECK-GLOBISEL-NEXT:    adr x16, :got_auth:func
; CHECK-GLOBISEL-NEXT:    ldr x0, [x16]
; CHECK-GLOBISEL-NEXT:    autia x0, x16
; CHECK-GLOBISEL-NEXT:    ret
entry:
      ret ptr @func
}

!llvm.module.flags = !{!0, !1}
!0 = !{i32 1, !"aarch64-elf-pauthabi-platform", i32 268435458}
!1 = !{i32 1, !"aarch64-elf-pauthabi-version", i32 128}
